version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - wordpress-files:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
    labels:
      - traefik.enable=true
      - traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.wordpress.entrypoints=websecure
      - traefik.http.routers.wordpress.tls.certresolver=letsencrypt
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  wordpress:
    image: wordpress:php8.4-fpm-alpine
    volumes:
      - wordpress-files:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${SERVICE_USER_WORDPRESS}
      WORDPRESS_DB_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://${DOMAIN}');
        define('WP_SITEURL', 'https://${DOMAIN}');
        define('FORCE_SSL_ADMIN', true);
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mariadb:
    image: mariadb:11
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_ROOT}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${SERVICE_USER_WORDPRESS}
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_WORDPRESS}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  wordpress-files:
  mariadb-data:
